In [2]:
import requests
import pandas as pd

In [3]:
url = 'https://en.wikipedia.org/wiki/States_of_Brazil'
html = requests.get(url).content

In [5]:
df_list = pd.read_html(html)

In [9]:
df = df_list[1]
df

,Flag and name,Code,Capital,Area(km2)[1],Population(2019)[2],"Density (perkm2, 2019)","GDP (R$millions, 2016)[3]",HDI(2017)[4]
0,Acre,AC,Rio Branco,164124,881935,5.37,13751,0.719
1,Alagoas,AL,Maceió,27843,3337357,119.86,49456,0.683
2,Amapá,AP,Macapá,142471,845731,5.94,14339,0.740
3,Amazonas,AM,Manaus,1559168,4144597,2.66,89017,0.733
4,Bahia,BA,Salvador,564723,14873064,26.34,258649,0.714
5,Ceará,CE,Fortaleza,148895,9132078,61.33,138379,0.735
6,Distrito Federal,DF,Brasília,5761,3015268,523.41,235497,0.850
7,Espírito Santo,ES,Vitória,46074,4018650,87.22,109227,0.772
8,Goiás,GO,Goiânia,340126,7018354,20.63,181692,0.769
9,Maranhão,MA,São Luís,329642,7075181,21.46,85286,0.687
10,Mato Grosso,MT,Cuiabá,903207,3484466,3.86,123834,0.774
11,Mato Grosso do Sul,MS,Campo Grande,357146,2778986,7.78,91866,0.766
12,Minas Gerais,MG,Belo Horizonte,586521,21168791,36.09,544634,0.787
13,Pará,PA,Belém,1245759,8602865,6.91,138068,0.698
14,Paraíba,PB,João Pessoa,56467,4018127,71.16,59089,0.722
15,Paraná,PR,Curitiba,199305,11433957,57.37,401662,0.792
16,Pernambuco,PE,Recife,98068,9557071,97.45,167290,0.727
17,Piauí,PI,Teresina,251617,3273227,13.01,41406,0.697
18,Rio de Janeiro,RJ,Rio de Janeiro,43750,17264943,394.62,640186,0.796
19,Rio Grande do Norte,RN,Natal,52810,3506853,66.41,59661,0.731
20,Rio Grande do Sul,RS,Porto Alegre,281707,11377239,40.39,408645,0.787
21,Rondônia,RO,Porto Velho,237765,1777225,7.47,39451,0.725
22,Roraima,RR,Boa Vista,224274,605761,2.70,11011,0.752
23,Santa Catarina,SC,Florianópolis,95731,7164788,74.84,256661,0.808
24,São Paulo,SP,São Paulo,248219,45919049,184.99,2038005,0.826
25,Sergipe,SE,Aracaju,21927,2298696,104.83,38867,0.702
26,Tocantins,TO,Palmas,277720,1572866,5.66,31576,0.743

In [10]:
df.columns

Index(['Flag and name', 'Code', 'Capital', 'Area(km2)[1]',
       'Population(2019)[2]', 'Density (perkm2, 2019)',
       'GDP (R$millions, 2016)[3]', 'HDI(2017)[4]'],
      dtype='object')

In [11]:
df.columns = ['state', 'UF', 'Capital', 'Area(km2)',
       'Population(2019)', 'Density (perkm2, 2019)',
       'GDP (R$millions, 2016)', 'HDI(2017)']

In [12]:
df.head(2)

,state,UF,Capital,Area(km2),Population(2019),"Density (perkm2, 2019)","GDP (R$millions, 2016)",HDI(2017)
0,Acre,AC,Rio Branco,164124,881935,5.37,13751,0.719
1,Alagoas,AL,Maceió,27843,3337357,119.86,49456,0.683

In [13]:
df.to_csv('../data/brazil_states_info.csv')

## IDH per City

In [ ]:
https://www.br.undp.org/content/brazil/pt/home/idh0/rankings/idhm-municipios-2010.html

In [14]:
url = 'https://www.br.undp.org/content/brazil/pt/home/idh0/rankings/idhm-municipios-2010.html'
html = requests.get(url).content
df_list = pd.read_html(html)

In [16]:
df = df_list[0]
df

,Ranking IDHM 2010,Município,IDHM 2010,IDHM Renda 2010,IDHM Longevidade 2010,IDHM Educação 2010
0,1 º,São Caetano do Sul (SP),862,0891,0887,811
1,2 º,Águas de São Pedro (SP),854,0849,0890,825
2,3 º,Florianópolis (SC),847,0870,0873,800
3,4 º,Balneário Camboriú (SC),845,0854,0894,789
4,4 º,Vitória (ES),845,0876,0855,805
...,...,...,...,...,...,...
5560,5560 º,Uiramutã (RR),453,0439,0766,276
5561,5562 º,Marajá do Sena (MA),452,0400,0774,299
5562,5563 º,Atalaia do Norte (AM),450,0481,0733,259
5563,5564 º,Fernando Falcão (MA),443,0417,0728,286
5564,5565 º,Melgaço (PA),418,0454,0776,207

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5565 entries, 0 to 5564
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ranking IDHM 2010      5565 non-null   object
 1   Município              5565 non-null   object
 2   IDHM 2010              5565 non-null   int64
 3   IDHM Renda 2010        5565 non-null   object
 4   IDHM Longevidade 2010  5565 non-null   object
 5   IDHM Educação 2010     5565 non-null   int64
dtypes: int64(2), object(4)
memory usage: 261.0+ KB